title: Raghwendra Dey
subtitle: A Tech Enthusiast, poet and a continuous learner
description: >- # this means to ignore newlines until "baseurl:"
  Raghwendra Dey - A Tech Enthusiast, poet and a continuous learner

url: https://raghwendra-dey.github.io # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog
# github: [metadata]

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Contact Me
      url : /contact


# Edit these details

author_logo: profile.jpeg
author: Raghwendra Dey
author_bio: Hi, This is Raghwendra Dey.  I am Pre-final year undergraduate of the department of Electrical Engg,  IIT Kharagpur. My interests lies in Software Engg, Algorithms and Data Structures, Web Development, Deep Learning, Machine Learning... I am passionate about applying my knowledge of computer in solving real world problems, and change the world for good. I am a very good team player and a fast learner. Apart from these, I enjoy doing yoga, and am a great lover of hindi poetry.
author_email: "kumarraghav075@gmail.com"
author_location: Kharagpur, India
author_website_url: "https://raghwendra-dey.github.io"
typewrite-text: A Tech Enthusiast, poet and a continuous learner

author_work_experiences:
            - company_name: Aerial Robotics Kharagpur
              company_logo: ark_logo.png
              company_url: https://github.com/arl-kgp
              designation: Software Team Member
              description: 
                - Developed and Implemented various algorithms for efficient localization and Path planning of drones based on ROS (Robot Operating System).
                - Worked on various computer vision techniques for effective detection of shapes and features in an image.
                - Worked on various controllers for effective controlling of drones and obstacle avoidance.
                - Deployed an ORBSLAM2 based indoor localisation algorithm and realtime 3D mapping and object detection using stereo cameras.
              visibility: true
#             - company_name: Asayer
#               company_logo: asayer.png
#               company_url: https://asayer.io
#               designation: Cloud Engineer
#               description: 
#                 - Adapted macOS to the cloud.
#                 - Automated iOS simulator and Safari Browser workloads.
#                 - Designed and developed a real-time monitoring dashboard for managing virtual machines and data inside Asayer.io
#               visibility: true
#             - company_name: Wizzlabs
#               company_logo: wizzlabs.png
#               company_url: https://www.wizzlabs.com
#               designation: Part-Time Software Developer
#               description: 
#                 - Developed and deployed desktop application to enhance user's web browsing experience.
#                 - Designed and implemented a framework to create software installer/uninstaller on Windows.
#                 - Build an iOS web Browser with an intuitive user interface and a custom video player that adds surround sound.
#               visibility: true

author_education_details:
              - college_logo: iit.jpeg
                college_name: IIT Kharagpur
                college_url: http://www.iitkgp.ac.in/
                college_degree: Bachelor of Technology (B. Tech.)
                description: Major in Instrumentation Engg, with Minor in Computer Science Engg.<br> 2018-2022
                visibility: true
              # - college_logo: insat.jpg
              #   college_name: INSAT
              #   college_url: http://www.insat.rnu.tn
              #   college_degree: CS Engineer
              #   description: Bachelor of Software Developement
              #   visibility: true

author_project_details:
              - project_thumbnail: chest-xray.jfif
                project_title: Covid-19 Detection using Chest X-Ray Images
                project_description: DL-based solution with transfer learning Resnet model for covid-19 detection using chest X-Ray images. 
                project_url: https://github.com/Raghwendra-Dey/covid19_cxr_detection
                github: https://github.com/Raghwendra-Dey/covid19_cxr_detection
                visibility: true
              - project_thumbnail: prod_meter_logo.png
                project_title: Productivity Meter
                project_description: A javascript based app to measure productivity by keeping track of small time wastage which generally goes un-noticed.
                project_url: https://github.com/Raghwendra-Dey/productivity_meter
                github: https://github.com/Raghwendra-Dey/productivity_meter
                visibility: true
#               - project_thumbnail: enahouni1.png
#                 project_title: Ena Houni
#                 project_description: A Platform built with colleges from Think.iT for volunteering during COVID-19 pandemic lockdown
#                 project_url: https://enahouni.com
#                 visibility: true
#               - project_thumbnail: codenroll.png
#                 project_title: Code'n'Roll
#                 project_description: A competitive programming platform with cloud based code execution and assessement
#                 project_url: https://codenroll.think-it.io
#                 visibility: true
#               - project_thumbnail: crunchy.png
#                 project_title: Crunchy
#                 project_description: Crunchy is a lightweight Browser with a great User Experience, compatible with all iOS devices (iPhones, iPads)
#                 github: https://github.com/WassimKallel/Crunchy
#                 visibility: true

# social links
github_username:  raghwendra-dey
facebook_username: raghwendra.dey
linkedin_username: raghwendra-dey


#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )
disqus_shortname: raghwendradey


# formspree (contact form)
formspree_email: raghavrambo007@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-168805110-1

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus
  - jemoji


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
